# Generated by Django 3.2.8 on 2021-10-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='화물명')),
                ('priority', models.CharField(choices=[('WEIGHT', '무게'), ('VOLUME', '부피')], help_text='금액을 적용할 우선순위', max_length=20, verbose_name='우선순위')),
                ('price_per_weight', models.IntegerField(verbose_name='무게당 금액')),
                ('price_per_volume', models.IntegerField(verbose_name='부피당 금액')),
            ],
        ),
    ]
